### ISSUE TITLE
UX deployment Feature

### ISSUE THREAD

**Issue by shdobxr** [CloudWanderer-io/PolicyGlass#22]
Really like the approach with PolicyGlass, but was wondering if there was a method to deploy a local sandbox capability. This way usage of policyglass is private. Not inferring that nefarious things are being done with inputs provided to the current sandbox.

**Comment by Sam-Martin** [comment]
Hi @shdobxr,
PolicyGlass is _really_ a Python package, so running it locally is the first-class use case! Just run `pip install policyglass` and follow the [instructions in the docs](https://policyglass.cloudwanderer.io/en/latest/). 

The sandbox just exists in order to make it easy to try out if you don't have a Python setup handy.

If you wanted to play around with deploying your own version of the sandbox react app and API you can find the source code for both here: https://github.com/CloudWanderer-io/policyglass-sandbox
There are no deployment instructions as it stands as it's just intended for the official sandbox at [http://sandbox.policyglass.cloudwanderer.io/](http://sandbox.policyglass.cloudwanderer.io/) but there's nothing stopping you from using the same code to deploy your own version in your own AWS account!

**Comment by dan-osms** [comment]
Thanks so much. That is somewhat what I considered, but this provides foundation to move forward with building my local sandbox. Much thanks!
